### ISSUE TITLE
Some environments are missing initial positions

### ISSUE THREAD

**Issue by MatanArk** [aqeelanwar/PEDRA#10]
I wanted to use outdoor_courtyard environment and couldn't because it didn't have an initial positions function

**Comment by aqeelanwar** [comment]
PEDRA was just updated to version 2.0. You can update.
This version supports multiple drones and more environments than PEDRA 1.0
outdoor_courtyard is supported in PEDRA2.0.

**Comment by MatanArk** [comment]
Thank you very much, I will update and try
