### ISSUE TITLE
msgpackrpc.error.TimeoutError : Request timed out

### ISSUE THREAD

**Issue by hshshs30202** [aqeelanwar/PEDRA#13]
msgpackrpc.error.TimeoutError : Request timed out
![image](https://user-images.githubusercontent.com/40173435/76985945-591e9f00-6984-11ea-87ff-bd68c598e9ab.png)

Here is my issue.. I cannot find a solution searching for google..
The version of msgpack, airsim is same with requirements_gpu.txt

**Comment by ShuboLiu** [comment]
Hi, have you solved this problem? I have the same problem. Can you please tell me how to solve it?

**Comment by gaviny1** [comment]
I also kept getting this error after one success. I then resolved it by updating the AirSim IP address.
