### ISSUE TITLE
'PedraAgent' object has no attribute 'save_network'

### ISSUE THREAD

**Issue by vatsal278** [aqeelanwar/PEDRA#29]
ater 8000 iter. the training stops with message 
global - Switching Target Network
------------- Error -------------
<class 'AttributeError'> DeepQLearning.py 333
'PedraAgent' object has no attribute 'save_network'

**Comment by aqeelanwar** [comment]
The issue has been fixed. You can either download the repo again or do the following

On line 333 replace
`global_agent.save_network`
with
`global_agent.network_model.save_network`

Let me know if this works.

**Comment by vatsal278** [comment]
yeah i was about to make a pull request as it worked for anyways thanks
