### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by nilesh-hegde** [aqeelanwar/PEDRA#31]
I had a few questions regarding the code and hope you could clear them
1. Why are there so many network architectures in network.py
2. Will the performance be altered with change in architecture
3. And where can I find more information regrading how the agent is rewarded and it is leading to changes in weights

**Comment by aqeelanwar** [comment]
Hello,

1. There are multiple network available in the code to select from. You can even create your network by following the templates provided in network.py
2. Yes. The complexity of the network architecture directly impacts the performance.
3. You might find these paper useful.
https://arxiv.org/pdf/1910.05547.pdf
https://arxiv.org/pdf/1807.08241.pdf

**Comment by nilesh-hegde** [comment]
Thank you
