### ISSUE TITLE
main.py run error

### ISSUE THREAD

**Issue by kfuller96** [aqeelanwar/PEDRA#50]
Hi,
When I run the main.py script after editing the config files, I get this error. Are you able to advise on how to fix it?
![Capture](https://user-images.githubusercontent.com/48900464/88455255-27c85980-ceb7-11ea-9683-f1b8349ead86.PNG)

Kind regards,
Kevin Fuller

**Comment by aqeelanwar** [comment]
Hello Kevin,

Can you share the package details installed in your virtual env using the following?
```conda activate myenv ```
```pip freeze```

**Comment by kfuller96** [comment]
Hi aqeel, i fixed this issue by installing "scipy" in the virtual env

**Comment by aqeelanwar** [comment]
Great. Since the problem is fixed, I will go ahead and close the issue.
