### ISSUE TITLE
CUDA dll import error

### ISSUE THREAD

**Issue by kfuller96** [aqeelanwar/PEDRA#51]
Hi,
When i try and run the python main.py file, i get this error under the environment logs. I can't install CUDA 8.0 as it's too old for my Nvidia driver and CUDA 11.0 (Current version) leads to the same error. 

Any advice on how it can be fixed? Thanks a lot in advance.
![Capture](https://user-images.githubusercontent.com/48900464/88495544-94e60700-cffd-11ea-968c-e384f025b16e.PNG)

**Comment by aqeelanwar** [comment]
Hello,

Can you check if its a generic error running the following in python
`import tensorflow as tf`

I remember having issues regarding installing the correct CUDA version. I can check and share details on which version I used if you want.

**Comment by kfuller96** [comment]
Hi Aqeel,
Run this in the virtual env or just in the general install?

**Comment by aqeelanwar** [comment]
I meant execute in the python shell. In short, use the following commands

1. Open a terminal and activate your environment
``` conda activate myenv```
2. Start python shell
```python```
3. Type the following command and enter
```import tensorflow as tf```

**Comment by kfuller96** [comment]
My apologies, Here is the output
![Capture](https://user-images.githubusercontent.com/48900464/88921213-7d36a900-d2b1-11ea-937c-00c5025ac3dd.PNG)

**Comment by aqeelanwar** [comment]
I use CUDA 9.0 on my GTX1080. May be try installing that.
Yes, the code will work on your GPU.

**Comment by kfuller96** [comment]
Tried 9.0, same issue. But found this https://www.tensorflow.org/install/source_windows tutorial. Should I try and install tensorflow using these instructions and check if that fixes it?

**Comment by aqeelanwar** [comment]
Yes. You should try that

**Comment by kfuller96** [comment]
Alright, I had to install CUDA 8.0 and then cuDNN 6.0. that fixed everything.

**Comment by khlaifiabilel** [comment]
I have solved this particular problem by creating a Conda environment "python3.6".
Tested on both Windows 11 and Ubuntu 20 & 22.
Please make sure to follow @egoraptor09 recommendations
