### ISSUE TITLE
A problem in extracting environment

### ISSUE THREAD

**Issue by Elnaz7393** [aqeelanwar/PEDRA#54]
![Annotation 2020-08-17 202504](https://user-images.githubusercontent.com/53965843/90416517-d121fa00-e0c7-11ea-866d-4838d5b4bf9f.jpg)
Hi, 
When I wanted to extract indoor_updown.rar I got this error. 
Would you help me with this?

**Comment by aqeelanwar** [comment]
Can you please try downloading and extracting some other environment and see if the problem still persists? This will help me troubleshoot if the indoor_updown.rar is corrupted.

**Comment by Elnaz7393** [comment]
No the problem is just with indoor_updown.rar. The other ones are ok and I could use them.

**Comment by aqeelanwar** [comment]
I have updated the environment. It should work fine now.
