### ISSUE TITLE
Getting real time output 

### ISSUE THREAD

**Issue by Elnaz7393** [aqeelanwar/PEDRA#55]
I need to use realtime images from the unreal environments and use them as input for my model to check if the current view is proper for moving forward or not and if it's not good my program calculates the angle and commands the drone to rotate. I want to do this at move_around mode.
How can I use `get_MonocularImageRGB()` to get image? I don't know what the arguments are for this function and what the output is. I don't have any idea what to do.
Please help me with what actions should I perform.

**Comment by aqeelanwar** [comment]
The associated module can be found in aux_functions.py
https://github.com/aqeelanwar/PEDRA/blob/eb4e69aa3650ea4a96ee89104007ceecf7fb715f/aux_functions.py#L338

**Comment by Elnaz7393** [comment]
I found it but what are `client` and `vehicle_name`?

**Comment by Elnaz7393** [comment]
Hi 
I tried to get `client` value(I'm not sure if I said it correct) from `client, old_posit, initZ = connect_drone(ip_address=cfg.ip_address, phase=cfg.mode, num_agents=cfg.num_agents)` but this error occured
![image](https://user-images.githubusercontent.com/53965843/90629841-46f7a400-e235-11ea-826a-2129f69eb99e.png)

**Comment by aqeelanwar** [comment]
Can you please share teh content of your config.cfg file?

**Comment by Elnaz7393** [comment]
Thanks for your incredible code. 
The problem is solved by changing `mode` in config.cfg from `move_around` to `infer`.
