### ISSUE TITLE
How to add your drones into customized environments? Could you provide source codes of your environments?

### ISSUE THREAD

**Issue by BenoitKAO** [aqeelanwar/PEDRA#65]
Thank you for your marvelous work!

How to add your drones into customized environments?

Could you provide source codes of your environments?

Any help is appreciated.

**Comment by aqeelanwar** [comment]
Hello,

The source project file is not available for now. We plan on releasing it soon.

**Comment by Maryamr314** [comment]
Is your source project available now?
