### ISSUE TITLE
Loading pretrained alexnet

### ISSUE THREAD

**Issue by JanMikicki** [aqeelanwar/PEDRA#69]
I was trying to load AlexNet (I assume?) pretrained on ImageNet, as described in this outdated blog post [here](https://towardsdatascience.com/deep-reinforcement-learning-for-drones-in-3d-realistic-environments-36821b6ee077). I used _imagenet.npy_ linked there and got "unable to open table" error:
![image](https://user-images.githubusercontent.com/13591149/99158536-04c6ed00-26d4-11eb-9216-68776c94457e.png)

Is this feature deprecated or is it a problem on my end? Also, is it even good idea to start with ImageNet pretrained net and if so, which format to use, .npy?

**Comment by aqeelanwar** [comment]
@JanMikicki 
The Imagenet weights in the models folder as mentioned in the outdated blog post is for alexnet network. If the network selected by you is different than alexnet, you will not be able to load the weights, and hence the error. You can
1. Either use alexnet as the underlying neural network to be trained
2. Or don't use imagenet weights as initialization

I realized that the drone navigation problem can be solved using a much smaller network (C3F2) that the heavy alexnet network, In the case of C3F2 network, you can train it from scratch and it won't take long (atleast not as long as alexnet network would)
