### ISSUE TITLE
unable to see screens during simulation

### ISSUE THREAD

**Issue by edsun123** [aqeelanwar/PEDRA#73]
I do not see the simulation screen with the drone. This includes the depth map and the segmentation map.

However, I can see the floorplan and the front facing camera.

**Comment by aqeelanwar** [comment]
Hello,

Did you try using the key 1, 2, 3?
You can find more information here
https://github.com/aqeelanwar/PEDRA/blob/master/unreal_envs/readme.md#environment-supported-features

**Comment by edsun123** [comment]
Yes, I have tried keys 1,2,3 because 3 was able to produce the front-facign camera. 

I think this is an issue with airsim.

**Comment by aqeelanwar** [comment]
Can you please share the screenshot?

**Comment by edsun123** [comment]
Here is screen shot in train mode: 
![Train_ScreenShot](https://user-images.githubusercontent.com/34005715/102001353-6bcdc680-3cbf-11eb-870f-77eb533afd2c.PNG)

**Comment by aqeelanwar** [comment]
Try using the key 'F'. This will enable the cameras and you will see the big black screen replaced with the feed from the front facing camera. Then try using keys 1 and 2.

**Comment by edsun123** [comment]
Thank you! This helped.

 Is the key 'F' from the airsim instructions? 

(i can only find a reference of it https://github.com/microsoft/AirSim/blob/master/docs/using_car.md)

**Comment by aqeelanwar** [comment]
Yes it is from AirSim. The 'F' key enables the graphics rendering. When it is enabled, only then you can view the depth and segment map in the simualtion. This rendering however doesn't affect the backedn python API. Python can still 'see' these images. Its just that these are not beging rendered for the users to see in the simualtion.

Graphics rendering for unreal simulation can take up significant compute power. So, I intentionally disable it when generating the settings.json file (No Display). This helps during the training phase, and each training iteration is much faster (about x2 times on GTX 1080) when the rendering is disabled. This means total training time is reduced by almost half.

**Comment by edsun123** [comment]
Great! Thank you for the explanation. Hopefully this will be helpful for others. 

I will be closing this issue.
