### ISSUE TITLE
Link for downloading environments is down.

### ISSUE THREAD

**Issue by meurissemax** [aqeelanwar/PEDRA#78]
Hello,

I just found this repository! Unfortunately, I see that the download link for the environments is no longer available. Is it possible to get a new one?

**Comment by aqeelanwar** [comment]
Hello,

I have refreshed the existing link. The environment files should be available at the link now.
Let me know if you can access them now.

**Comment by meurissemax** [comment]
Hello,

It works perfectly, thank you!
