### ISSUE TITLE
Environment download not working

### ISSUE THREAD

**Issue by TurnerDD** [aqeelanwar/PEDRA#87]
Correlation ID: e768d69f-6034-0000-d45a-af6fe8cad4f6
Date and Time: 6/28/2021 1:48:40 PM
URL: https://gtvault-my.sharepoint.com/personal/manwar8_gatech_edu/_layouts/15/guestaccess.aspx?e=HtI1ck&share=EnCc2xWKBCpIkWseegrp1EYB69y0zS3nLqzsaSfE-KAD4g

**Comment by Shelling1412** [comment]
Excuse me, have you got the required environmental documents？I still got 404 from this link:(
